apiVersion: v1
kind: Service
metadata:
  name: <name_service>
  labels:
    app: <label_service>
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
  selector:
   app: <label_service>
